apiVersion: apps/v1
kind: Deployment
metadata:
  name: perf-analyzer-webapp
  labels:
    app: perf-analyzer-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: perf-analyzer-webapp
  template:
    metadata:
      labels:
        app: perf-analyzer-webapp
    spec:
      containers:
        - name: perf-analyzer-webapp
          image: cadugrillo/perf-analyzer-webapp:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.5"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: perf-analyzer-webapp-service
spec:
  selector:
    app: perf-analyzer-webapp
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: perf-analyzer
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:  
  - http:
      paths:
      - path: /performance-analyzer
        pathType: Prefix
        backend:
          service:
            name: perf-analyzer-webapp-service
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perf-analyzer-api
  labels:
    app: perf-analyzer-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: perf-analyzer-api
  template:
    metadata:
      labels:
        app: perf-analyzer-api
    spec:
      containers:
        - name: perf-analyzer-api
          image: cadugrillo/perf-analyzer-api:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.5"
              memory: "1024Mi"
            limits:
              cpu: "1"
              memory: "2048Mi"
          ports:
          - containerPort: 4300
---
apiVersion: v1
kind: Service
metadata:
  name: perf-analyzer-api-service
spec:
  selector:
    app: perf-analyzer-api
  ports:
    - port: 4300
      targetPort: 4300