#stage 1
FROM node:latest as node

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm install -g @angular/cli
#When local deployment comment the following line and uncomment the next one after
RUN ng build --base-href=/performance-analyzer/ --output-path=/dist
#RUN ng build --configuration=production-local --base-href=/performance-analyzer/ --output-path=/dist

#stage 2
FROM nginx:alpine

#When local deployment comment the following line and uncomment the next one after
COPY --from=node /dist /usr/share/nginx/html/performance-analyzer
#COPY nginx-custom.conf /etc/nginx/conf.d/default.conf
COPY nginx-custom-local.conf /etc/nginx/conf.d/default.conf
EXPOSE 80